# Generated by Django 5.2.8 on 2025-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Allergen Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Allergen Description')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Allergen Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Cuisine Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Cuisine Description')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cuisine Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Level Name')),
                ('tier', models.PositiveSmallIntegerField(unique=True, verbose_name='Level Tier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Level Description')),
                ('min_xp', models.PositiveIntegerField(verbose_name='Minimum Experience')),
                ('max_xp', models.PositiveIntegerField(verbose_name='Maximum Experience')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Level Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('category', models.CharField(choices=[('dietary', 'Dietary'), ('method', 'Method'), ('occasion', 'Occasion')], max_length=20, verbose_name='Tag Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Technique Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Technique Description')),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'ordering': ['name'],
            },
        ),
    ]
