# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='User Biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='User Avatar')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Location')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='User Website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='User Cuisine Experience Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cuisines', to='shared.cuisine', verbose_name='User Cuisine')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cuisines_at_this_level', to='shared.level', verbose_name='User Cuisine Level')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='profiles.userprofile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Cuisine Record',
                'verbose_name_plural': 'User Cuisine Records',
                'ordering': ['-experience'],
                'unique_together': {('user_profile', 'cuisine')},
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('anaphylaxis', 'Anaphylaxis')], max_length=20, verbose_name='User Allergy Severity')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='User Allergy Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_allergies', to='shared.allergen')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'User Allergy',
                'verbose_name_plural': 'User Allergies',
                'ordering': ['severity'],
                'unique_together': {('user_profile', 'allergen')},
            },
        ),
        migrations.CreateModel(
            name='UserTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='User Technique Experience Points')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_techniques_at_this_level', to='shared.level', verbose_name='User Technique Level')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_techniques', to='shared.technique', verbose_name='User Technique')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='profiles.userprofile', verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Technique Record',
                'verbose_name_plural': 'User Technique Records',
                'ordering': ['-experience'],
                'unique_together': {('user_profile', 'technique')},
            },
        ),
    ]
