# Generated by Django 5.2.8 on 2025-11-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Recipe Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Recipe Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('private', 'Private')], default='draft', max_length=15, verbose_name='Recipe Status')),
                ('course', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('lunch', 'Lunch'), ('appetiser', 'Appetiser'), ('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=20, verbose_name='Recipe Course')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], default='medium', max_length=15, verbose_name='Recipe Difficulty')),
                ('prep_time', models.PositiveIntegerField(default=10, verbose_name='Recipe Preparation Time')),
                ('cook_time', models.PositiveIntegerField(default=30, verbose_name='Recipe Cooking Time')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Recipe Servings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='profiles.userprofile', verbose_name='Recipe Author')),
                ('parent_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='recipes.recipe')),
                ('tags', models.ManyToManyField(related_name='recipes', to='shared.tag', verbose_name='Recipe Tags')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Completion Notes')),
                ('time_taken', models.PositiveIntegerField(verbose_name='Time Taken')),
                ('steps_skipped', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Steps Skipped')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='recipes.recipe', verbose_name='Recipe Completed')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='profiles.userprofile', verbose_name='User Completed')),
            ],
            options={
                'verbose_name': 'Completion Record',
                'verbose_name_plural': 'Completion Records',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ingredient Order')),
                ('name', models.CharField(max_length=100, verbose_name='Ingredient Name')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ingredient Quantity')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ingredient Unit')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optional Ingredient?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ingredient Notes')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Related Recipe')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['order'],
                'unique_together': {('recipe', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RecipeAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(choices=[('trace', 'Trace'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, verbose_name='Recipe Allergy Amount')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Recipe Allergy Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='shared.allergen', verbose_name='Recipe Allergen')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Allergen',
                'verbose_name_plural': 'Recipe Allergens',
                'ordering': ['amount'],
                'unique_together': {('recipe', 'allergen')},
            },
        ),
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='shared.cuisine', verbose_name='Related Cuisine')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_cuisines_at_this_level', to='shared.level', verbose_name='Related Level')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='recipes.recipe', verbose_name='Related Recipe')),
            ],
            options={
                'verbose_name': 'Recipe Cuisine',
                'verbose_name_plural': 'Recipe Cuisines',
                'ordering': ['level__tier'],
                'unique_together': {('recipe', 'cuisine')},
            },
        ),
        migrations.CreateModel(
            name='RecipeTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_technique_at_this_level', to='shared.level', verbose_name='Related Level')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='recipes.recipe', verbose_name='Related Recipe')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes_technique_used_in', to='shared.technique', verbose_name='Related Technique')),
            ],
            options={
                'verbose_name': 'Recipe Technique',
                'verbose_name_plural': 'Recipe Techniques',
                'ordering': ['level__tier'],
                'unique_together': {('recipe', 'technique')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Step Order')),
                ('instruction', models.TextField(verbose_name='Step Instruction')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Step Duration')),
                ('is_timed', models.BooleanField(default=False, verbose_name='Timed Step?')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='Related Recipe')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ['order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_timed', False), ('duration__isnull', False), _connector='OR'), name='timed_steps_must_have_duration_set and vice versa')],
                'unique_together': {('recipe', 'order')},
            },
        ),
    ]
