# Generated by Django 5.2.8 on 2025-11-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='parent_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='recipes.recipe'),
        ),
    ]
